mysql:
  host: localhost
  port: 3306
  database: minecraft
  user: username
  password: password

musicConfig:
  music:
    maxLength: 8192
  volume:
    default: 2
    autoPlay: 0.5
    radius: 5
  cantPlayPublic:
    worldName: [""]

items:
  keyBoard:
    material: stone_hoe
    cmd: 1
  walkMan:
    material: stone_hoe
    cmd: 2
  cassette:
    material: iron_nugget
    cmd: 1
  sheetMusic:
    blank:
      material: iron_nugget
      cmd: 2
    written:
      material: iron_nugget
      cmd: 3

icons:
  material: wooden_shovel
  triangle:
    up: 1
    down: 2
    left: 3
    right: 4
    select: 5
  sheetMusic:
    scale:
      null-F#: 6
      F-E: 7
      D#-D: 8
      C#-C: 9
      B-A#: 10
      A-G#: 11
      G-F#: 12
    note:
      blank: 13
      red:
        up: 14
        down: 15
      aqua:
        up: 16
        down: 17
      green:
        up: 18
        down: 19
      yellow:
        up: 20
        down: 21