name: Man10Music
version: '1.0-SNAPSHOT'
main: io.github.itokagimaru.mun10music.Man10Music
api-version: '1.21'

permissions:
  man10music.admin:
    default: op

commands:
  mmusic:
    description: /mmusicコマンドのヘルプを表示
    usage: /mmusic [help]
